In [ ]:
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline

# **Linguistic Pipeline in a 🥜**

Text_01_1115, St01_d **Il contadino astrologo**

In [3]:
with open ("C:\\Users\\schia\\OneDrive - Alma Mater Studiorum Università di Bologna\\Desktop\\IMT\\TESI\\linguistic_pipeline_EEG\\data\\texts_1115\\01_1115.txt", 'r', encoding="utf-8")as infile:
    text = infile.read()

print(text)

Il contadino astrologo.
Un Re aveva perduto un anello prezioso. Cerca qua, cerca là, non si trova. Mise fuori un bando che
se un astrologo gli sa dire dov'è, lo fa ricco per tutta la vita. C'era un contadino senza un soldo, che non sapeva né leggere né scrivere, e si chiamava Gàmbara. "Sarà tanto difficile far l'astrologo? - si disse. – Mi ci voglio provare". E andò dal Re che lo prese in parola, e lo chiuse a studiare in una stanza. Dove c'erano solo un letto e un tavolo con un gran libraccio d'astrologia, e penna carta e calamaio. Gàmbara si sedette al tavolo e cominciò a scartabellare il libro senza capirci niente e a farci dei segni con la penna. Siccome non sapeva scrivere, venivano fuori dei segni ben strani, e i servi che entravano due volte al giorno a portargli da mangiare, si fecero l'idea che fosse un astrologo sapiente.
Questi servi erano stati loro a rubare l'anello, e con la coscienza sporca che avevano, le
occhiatacce che rivolgeva loro Gàmbara ogni volta che entravano, per darsi aria d'uomo d'autorità,
parevano loro occhiate di sospetto. Cominciarono ad aver paura d'essere scoperti, e non la finivano più con le riverenze.
Gàmbara, che astrologo non era, ma contadino, e perciò malizioso, subito aveva pensato che i servi dovessero saperne qualcosa. E pensò di farli cascare in un inganno.
Un giorno, all'ora in cui gli portarono il pranzo, si nascose sotto il letto. Entrò il primo dei servi e
non vide nessuno. Di sotto il letto, Gàmbara disse forte: - E uno! - il servo lasciò il piatto e si ritirò
spaventato.
Entrò il secondo servo: - E due! - e scappò via
anche lui.
Entrò il terzo: - E tre!
I servi si consultarono: - Ormai siamo scoperti, se l'astrologo ci accusa al Re, siamo spacciati.
Così decisero d'andare dall'astrologo e confessargli il furto. - Noi siamo povera gente, - gli fecero, - e se dite al Re quel che avete scoperto, siamo perduti.
- Io non vi tradirò, però voi fate quel che vi dico. Prendete l'anello e fatelo inghiottire a quel tacchino che c'è laggiù in cortile. Poi lasciate fare a me.
Il giorno dopo Gàmbara si presentò al Re e gli disse che dopo lunghi studi era riuscito a sapere
dov'era l'anello.
- E dov'è?
- L'ha inghiottito un tacchino.
Fu sventrato il tacchino e si trovò l'anello. Il Re colmò di ricchezze l'astrologo e diede un pranzo in
suo onore.
Tra le tante pietanze fu portato in tavola un piatto di gamberi. Bisogna sapere che in quel paese era la prima volta che se ne vedevano, regalo d'un Re d'altro paese.
- Tu che sei astrologo, - disse il Re al contadino, - dovresti sapermi dire come si chiamano questi che sono qui nel piatto.
Il poveretto di bestie così non ne aveva mai viste. E disse tra sé, a mezza voce: - Ah, Gàmbara, Gàmbara. Sei finito male.
- Bravo! - disse il Re. - Hai indovinato: quello è il nome:
gamberi! Sei il più grande astrologo del mondo.

## **First Step**
*.py file* = `nlp_pipeline/processor.py`

- tokenization
- mwe
- lemmatization
- PoS
- Deapparse/Consituency
- **Zipf's frequency**
- **Type of words (*content, function*)**
- AoA

- **Statistics of texts**

In [4]:
df = pd.read_csv("C:\\Users\\schia\\OneDrive - Alma Mater Studiorum Università di Bologna\\Desktop\\IMT\\TESI\\linguistic_pipeline_EEG\\output\\output_1115\\01_1115\\01_1115.csv", sep=";", encoding="utf-8")
df.head()

,token_id,sentence_ids,tokens_no_punct,lemma_no_punct,PoS,depparse,head,constituency,AoA(m+sd),Zipf_freq,type_of_words
0,1,0,il,il,DET,det,contadino,(ROOT (f3 (sn (DET Il) (NOUN contadino) (sa (A...,NaN,"7,039560886",function
1,2,0,contadino,contadino,NOUN,root,ROOT,(ROOT (f3 (sn (DET Il) (NOUN contadino) (sa (A...,NaN,"3,787520326",content
2,3,0,astrologo,astrologo,ADJ,amod,contadino,(ROOT (f3 (sn (DET Il) (NOUN contadino) (sa (A...,NaN,"2,502677091",content
3,4,1,un,uno,DET,det,Re,(ROOT (f (sn (DET Un) (NOUN Re)) (ibar (AUX av...,NaN,"7,065833912",function
4,5,1,re,re,NOUN,nsubj,perduto,(ROOT (f (sn (DET Un) (NOUN Re)) (ibar (AUX av...,4.24 ± 1.76,"5,011715611",content

## **Statistics on the text**
*.py file* = `nlp_pipeline/processor.py`

In [29]:
df = pd.read_csv("C:\\Users\\schia\\OneDrive - Alma Mater Studiorum Università di Bologna\\Desktop\\IMT\\TESI\\linguistic_pipeline_EEG\\output\\output_1115\\summary_all_texts.csv")

df.head(1)

,text_id,num_tokens,num_sentences,num_types,TTR,TTR_lemmas,avg_sentence_length,Zipf_mean,percent_rare_words,Gulpease_index,num_function_words,num_content_words,num_verbs,num_adjectives,num_nouns,top_lemmas,top_bigrams
0,01_1115,519,41,261,0.503,0.374,15.24,5.29,12.75,70.37,287 (55.3%),229 (44.1%),102 (19.7%),22 (4.2%),105 (20.2%),"['il (7.1%)', 'e (5.2%)', 'essere (4.4%)', 'un...","['l anello (0.8%)', 'e si (0.6%)', 'l astrolog..."

## **1. Lexical Surprisal**

*.py file* = `nlp_pipeline/surprisal_entropy.py`

In [33]:
df_surp = pd.read_csv("C:\\Users\\schia\\OneDrive - Alma Mater Studiorum Università di Bologna\\Desktop\\IMT\\TESI\\linguistic_pipeline_EEG\\output\\output_1115\\01_1115\\suprisal_entropy01_1115.csv")

## **2. Lexical Entropy**

*.py file* = `nlp_pipeline/surprisal_entropy.py`

## **3. Semantic Dissimilarity**
*.py file* = `nlp_pipeline/semantic_dissimilarity.py`